[package]
name = "simpla_vortaro"
version = "0.1.0"
authors = ["panicbit <panicbit.dev@gmail.com>"]

[dependencies]
reqwest = "0.8.4"
serde = { version = "1.0.27", features = ["serde_derive"] }
percent-encoding = "1.0.1"
clap = "2.30.0"
colored = "1.6.0"
itertools = "0.7.6"
textwrap = { version = "0.9.0", features = ["term_size"] }
